-- Criando o Chema do BD
-- new_tablecreate schema  `BD2401`;

-- Excluindo o BD
-- DROP DATABASE `BD2401` ;

-- Criando tabela 
CREATE TABLE `BD2401`.`NEW_TABLE`(
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT, -- INTEIRO NÃO NULO QUE SE AUTO INCREMENTA
    `FIRTS_NAME` VARCHAR(20) NOT NULL, -- DETERMINA A VARIAVEL COM LOCAÇÕES VARIAVEIS NA MEMORIA NÃO NULO
    `ACTIVE` BIT(1) NULL DEFAULT 1, -- BIT TRUE OR FALSE (ATIVO OU INATIVO), ACEITA NULA, SE DETERMINADO NULO SERÁ DETERMINADO 1
	`WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, -- QUANDO ADICIONADO 
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (`ID_MEMBER`)
);

-- Inserindo dados na tabela
INSERT INTO `BD2401`.`NEW_TABLE` (`FIRTS_NAME`)
VALUES ('MAURICIO R ZONZATTO');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRTS_NAME`, `ACTIVE`)
VALUES ('OLIVIA GONZATTO', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRTS_NAME`, `ACTIVE`)
VALUES ('CECI GONZATTO', 0);

-- EXIBINDO/CONSULTANDO DADOS
SELECT * FROM `BD2401`.`NEW_TABLE`;